### PR TITLE
Resolve problems discovered while testing on macOS (fixes #58)

### LINKED ISSUE #58: Test Script Does Not Run on macOS
The test script just tries to get the chrome version using:
```
chrome_version=$(google-chrome --version)
```
But this is not sufficient for macOS where it's typically in the `/Applications/` directory.

Trying to run on macOS currently produces an error:
```
./scripts/test.sh: line 10: google-chrome: command not found
```

After resolving this, I also discovered that the bot test is failing intermittently on an M4 mac because the framework executes faster than the javascript can complete.

I am submitting a PR to resolve both of these issues.

### PR DESCRIPTION
**Pull request by raycardillo**
This PR resolves two issues I found when testing on macOS. See issue #58 for details.

1. Updates to the `scripts/test.sh` so that it will work "out of the box" on macOS. I did this in a way that should not interfere with existing users and provides the pattern for solving the same problem if it might arise on other platforms in the future.
2. The test in `tests/bot_detection/test_browserscan.py` does not wait long enough for the javascript to render the element in the DOM that the test is looking for. I added a small `page.wait()` that resolves this and now the tests pass consistently.

### CODE REVIEW

File: scripts/test.sh [hunk 1]
```diff
@@ -7,7 +7,14 @@ if [ "${#command[@]}" -eq 0 ]; then
   command=( "pytest" )
 fi
 
-chrome_version=$(google-chrome --version)
+chrome_cmd=("google-chrome")
+if [[ "$OSTYPE" == "darwin"* ]]; then
+  # macOS
+  chrome_cmd=("/Applications/Google Chrome.app/Contents/MacOS/Google Chrome")
+fi
+chrome_cmd+="--version"
```
Comment (stephanlensky) [inline scripts/test.sh:15]:
```suggestion
chrome_cmd+=("--version")
```

File: scripts/test.sh [hunk 2]
```diff
@@ -7,7 +7,14 @@ if [ "${#command[@]}" -eq 0 ]; then
...
+
+chrome_version="${chrome_cmd[@]}"
```
Comment (stephanlensky) [inline scripts/test.sh:17]:
```suggestion
chrome_version=$("${chrome_cmd[@]}")
```

**Review by stephanlensky — COMMENTED** [review]
I had to make two changes to get this to work properly on my machine, previously it was just printing:

```
Chrome version: google-chrome--version
```

**Comment by stephanlensky** [comment]
With those changes all seems to be working well though. Thank you for the submission 🙂

**Comment by khamaileon** [comment]
Fix it for me too, thank you.
